-- MySQL Script generated by MySQL Workbench
-- Fri Dec 16 00:14:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema biblioteca2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `biblioteca2` ;

-- -----------------------------------------------------
-- Schema biblioteca2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca2` DEFAULT CHARACTER SET latin1 ;
USE `biblioteca2` ;

-- -----------------------------------------------------
-- Table `biblioteca2`.`libros_2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca2`.`libros_2` ;

CREATE TABLE IF NOT EXISTS `biblioteca2`.`libros_2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_libro` VARCHAR(45) NULL DEFAULT NULL,
  `genero` VARCHAR(45) NULL DEFAULT NULL,
  `autor` VARCHAR(45) NULL DEFAULT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  `stock` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `biblioteca2`.`detalle_venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca2`.`detalle_venta` ;

CREATE TABLE IF NOT EXISTS `biblioteca2`.`detalle_venta` (
  `id` INT NOT NULL,
  `cantidad` VARCHAR(45) NULL DEFAULT NULL,
  `id_libro` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_libro_idx` (`id_libro` ASC) VISIBLE,
  CONSTRAINT `id_libro`
    FOREIGN KEY (`id_libro`)
    REFERENCES `biblioteca2`.`libros_2` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `biblioteca2`.`venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca2`.`venta` ;

CREATE TABLE IF NOT EXISTS `biblioteca2`.`venta` (
  `id` INT NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `total` DOUBLE NULL DEFAULT NULL,
  `id_detalle` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_detalle_idx` (`id_detalle` ASC) VISIBLE,
  CONSTRAINT `id_detalle`
    FOREIGN KEY (`id_detalle`)
    REFERENCES `biblioteca2`.`detalle_venta` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
